# Form implementation generated from reading ui file 'AddPassword.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(439, 339)
        Dialog.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        Dialog.setSizeGripEnabled(False)
        self.Image = QtWidgets.QLabel(parent=Dialog)
        self.Image.setGeometry(QtCore.QRect(0, -10, 321, 361))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("img/sabura2.png"))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 180, 141, 117))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GeneratePassword = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.GeneratePassword.setObjectName("GeneratePassword")
        self.verticalLayout.addWidget(self.GeneratePassword)
        self.OkButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.OkButton.setObjectName("OkButton")
        self.verticalLayout.addWidget(self.OkButton)
        self.CancelButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.verticalLayout.addWidget(self.CancelButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 70, 231, 86))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoginLine = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.LoginLine.setObjectName("LoginLine")
        self.verticalLayout_2.addWidget(self.LoginLine)
        self.PasswordLine = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.PasswordLine.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.PasswordLine.setObjectName("PasswordLine")
        self.verticalLayout_2.addWidget(self.PasswordLine)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AddPassword"))
        self.GeneratePassword.setText(_translate("Dialog", "Сгенерировать"))
        self.OkButton.setText(_translate("Dialog", "Ок"))
        self.CancelButton.setText(_translate("Dialog", "Отмена"))
