# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 644)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: black;\n"
"    background-color: #ffffff;\n"
"}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PswdList = QtWidgets.QListView(parent=self.centralwidget)
        self.PswdList.setGeometry(QtCore.QRect(390, 30, 519, 409))
        self.PswdList.setStyleSheet("")
        self.PswdList.setObjectName("PswdList")
        self.Image = QtWidgets.QLabel(parent=self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(10, 150, 361, 461))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("img/sabura.jpeg"))
        self.Image.setScaledContents(True)
        self.Image.setWordWrap(False)
        self.Image.setOpenExternalLinks(False)
        self.Image.setObjectName("Image")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Savepsvd"))
